<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns# article: http://ogp.me/ns/article# " lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Throw exception in C++ destructor | BaoLong</title>
<link href="../../../../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="alternate" type="application/rss+xml" title="RSS (en)" href="../../../../../rss.xml">
<link rel="alternate" type="application/rss+xml" title="RSS (zh_cn)" href="../../../../../zh_cn/rss.xml">
<link rel="canonical" href="https://baolonglin.github.io/posts/2016/12/7/throw-exception-in-destructor/">
<!--[if lt IE 9]><script src="../../../../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Baolong Lin">
<link rel="next" href="../../../../2017/3/2/restore-work-space/" title="Restore workspace" type="text/html">
<meta property="og:site_name" content="BaoLong">
<meta property="og:title" content="Throw exception in C++ destructor">
<meta property="og:url" content="https://baolonglin.github.io/posts/2016/12/7/throw-exception-in-destructor/">
<meta property="og:description" content="We should Prevent exceptions from leaving destructors as Effective C++ suggeust, and in that book, it also explains the reason: Now there are two simulataneously active exceptions, and that's one too ">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2016-12-07T00:00:00+01:00">
<link rel="alternate" hreflang="zh_cn" href="../../../../../zh_cn/posts/2016/12/7/throw-exception-in-destructor/">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Header and menu bar -->
<div class="container">
      <header class="blog-header py-3"><div class="row nbb-header align-items-center">
          <div class="col-md-3 col-xs-2 col-sm-2" style="width: auto;">
            <button class="navbar-toggler navbar-light bg-light nbb-navbar-toggler" type="button" data-toggle="collapse" data-target=".bs-nav-collapsible" aria-controls="bs-navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse bs-nav-collapsible bootblog4-search-form-holder">
                
            </div>
        </div>
          <div class="col-md-6 col-xs-10 col-sm-10 bootblog4-brand" style="width: auto;">
            <a class="navbar-brand blog-header-logo text-dark" href="https://baolonglin.github.io/">

            <span id="blog-title">BaoLong</span>
        </a>
          </div>
            <div class="col-md-3 justify-content-end align-items-center bs-nav-collapsible collapse flex-collapse bootblog4-right-nav">
            <nav class="navbar navbar-light bg-white"><ul class="navbar-nav bootblog4-right-nav">
<li class="nav-item"><a href="https://baolonglin.github.io/zh_cn/" rel="alternate" hreflang="zh_cn" class="nav-link">简体中文</a></li>

                    
                    
    
    <li class="nav-item">
    <a href="index.md" id="sourcelink" class="nav-link">Source</a>
    </li>


                    
            </ul></nav>
</div>
    </div>
</header><nav class="navbar navbar-expand-md navbar-light bg-white static-top"><div class="collapse navbar-collapse bs-nav-collapsible" id="bs-navbar">
            <ul class="navbar-nav nav-fill d-flex w-100">
<li class="nav-item">
<a href="../../../../../archive.html" class="nav-link">Archive</a>
                </li>
<li class="nav-item">
<a href="../../../../../categories/" class="nav-link">Tags</a>
                </li>
<li class="nav-item">
<a href="../../../../../rss.xml" class="nav-link">RSS feed</a>

                
            </li>
</ul>
</div>
<!-- /.navbar-collapse -->
</nav>
</div>

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        
        
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">Throw exception in C++ destructor</a></h1>

        <div class="metadata">
            <p class="byline author vcard"><span class="byline-name fn" itemprop="author">
                    Baolong Lin
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2016-12-07T00:00:00+01:00" itemprop="datePublished" title="2016-12-07 00:00">2016-12-07 00:00</time></a>
            </p>
                <p class="commentline">
        
    <a href="#disqus_thread" data-disqus-identifier="cache/posts/2016/12/7/throw-exception-in-destructor.html">Comments</a>


            
        </p>
<p class="sourceline"><a href="index.md" class="sourcelink">Source</a></p>

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <div>
<p>We should <code>Prevent exceptions from leaving destructors</code> as <strong>Effective C++</strong> suggeust, and in that book, it also explains the reason: <code>Now there are two simulataneously active exceptions, and that's one too many for C++</code>. Is not that program interupt when throw one exception? Why two exceptions will be throw out? Let's use one example to make those clear.</p>
<pre class="code literal-block"><span></span><span class="cp">#include</span> <span class="cpf">&lt;iostream&gt;</span><span class="cp"></span>
<span class="cp">#include</span> <span class="cpf">&lt;vector&gt;</span><span class="cp"></span>

<span class="k">class</span> <span class="nc">Exception</span>
<span class="p">{</span>
<span class="k">public</span><span class="o">:</span>
    <span class="n">Exception</span><span class="p">(</span><span class="kt">int</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span><span class="p">)</span> <span class="o">:</span> <span class="n">_i</span><span class="p">(</span><span class="n">i</span><span class="p">)</span> <span class="p">{</span>
    <span class="p">}</span>
    <span class="o">~</span><span class="n">Exception</span><span class="p">()</span> <span class="k">throw</span><span class="p">(</span><span class="kt">int</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span class="s">"Throw : "</span> <span class="o">&lt;&lt;</span> <span class="n">_i</span> <span class="o">&lt;&lt;</span> <span class="n">std</span><span class="o">::</span><span class="n">endl</span><span class="p">;</span>
        <span class="k">throw</span> <span class="n">_i</span><span class="p">;</span>        <span class="c1">// &lt;-- 1</span>
    <span class="p">}</span>
<span class="k">private</span><span class="o">:</span>
    <span class="kt">int</span> <span class="n">_i</span><span class="p">;</span>
<span class="p">};</span>

<span class="k">class</span> <span class="nc">OtherObject</span>
<span class="p">{</span>
<span class="k">public</span><span class="o">:</span>
    <span class="o">~</span><span class="n">OtherObject</span><span class="p">()</span> <span class="p">{</span>
        <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span class="s">"~OtherObject"</span> <span class="o">&lt;&lt;</span> <span class="n">std</span><span class="o">::</span><span class="n">endl</span><span class="p">;</span>
    <span class="p">}</span>
<span class="p">};</span>

<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span>
<span class="p">{</span>
    <span class="k">try</span> <span class="p">{</span>
        <span class="n">OtherObject</span> <span class="n">o</span><span class="p">;</span> <span class="c1">// &lt;-- 2</span>
        <span class="p">{</span>
            <span class="n">Exception</span> <span class="n">e</span><span class="p">(</span><span class="mi">10</span><span class="p">);</span>  <span class="c1">// &lt;-- 3</span>
            <span class="c1">//throw 3; // &lt;-- 4</span>
        <span class="p">}</span> <span class="c1">// &lt;-- 4</span>
        <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span class="s">"after throw"</span> <span class="o">&lt;&lt;</span> <span class="n">std</span><span class="o">::</span><span class="n">endl</span><span class="p">;</span> <span class="c1">// &lt;-- 5</span>
    <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="kt">int</span> <span class="n">i</span><span class="p">)</span> <span class="p">{</span>
        <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span class="s">"Catch : "</span> <span class="o">&lt;&lt;</span> <span class="n">i</span> <span class="o">&lt;&lt;</span> <span class="n">std</span><span class="o">::</span><span class="n">endl</span><span class="p">;</span> <span class="c1">// &lt;-- 6</span>
    <span class="p">}</span>

    <span class="k">try</span> <span class="p">{</span>
        <span class="n">std</span><span class="o">::</span><span class="n">vector</span><span class="o">&lt;</span><span class="n">Exception</span><span class="o">&gt;</span> <span class="n">v</span><span class="p">(</span><span class="mi">4</span><span class="p">);</span> <span class="c1">// &lt;-- 7</span>
    <span class="p">}</span> <span class="k">catch</span> <span class="p">(...)</span> <span class="p">{</span>
        <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span class="s">"Catch something"</span> <span class="o">&lt;&lt;</span> <span class="n">std</span><span class="o">::</span><span class="n">endl</span><span class="p">;</span> <span class="c1">// &lt;-- 8</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre>


<p>In the example above, use g++ 4.3.4, output looks like:</p>
<pre class="code literal-block"><span></span><span class="n">Throw</span> <span class="o">:</span> <span class="mi">10</span>
<span class="o">~</span><span class="n">OtherObject</span>
<span class="n">Catch</span> <span class="o">:</span> <span class="mi">10</span>
<span class="n">Throw</span> <span class="o">:</span> <span class="mi">0</span>
<span class="n">Throw</span> <span class="o">:</span> <span class="mi">0</span>
<span class="n">terminate</span> <span class="n">called</span> <span class="n">after</span> <span class="n">throwing</span> <span class="n">an</span> <span class="n">instance</span> <span class="n">of</span> <span class="s1">'int'</span>
<span class="n">Aborted</span> <span class="o">(</span><span class="n">core</span> <span class="n">dumped</span><span class="o">)</span>
</pre>


<p><strong>NOTE:</strong> in g++ 6.2.1, it only get one <code>Throw : 0</code>. Because the STL vector's destructor default is noexcept, it terminate the program met the first exception.</p>
<p>What happends? The program is interrupt when object <code>e</code> throws exception in destructor, that's why position 5 is not executed.
But C++ doing a little bit more, it tries to release the object inside the try block, that's why <code>~OtherObject</code> is printed out.
The exception throw by the destructor is caught successfully, position 6 is executed.
What happends at position 7, why position 8 is not executed?
Do another test, if we try to open the position 3, throw exception before object <code>e</code> to be destruct, what will happen? In that case two exceptions are going to be throw out. Now the console output looks like:</p>
<pre class="code literal-block"><span></span><span class="n">Throw</span> <span class="o">:</span> <span class="mi">10</span>
<span class="n">terminate</span> <span class="n">called</span> <span class="n">after</span> <span class="n">throwing</span> <span class="n">an</span> <span class="n">instance</span> <span class="n">of</span> <span class="s1">'int'</span>
<span class="n">Aborted</span> <span class="o">(</span><span class="n">core</span> <span class="n">dumped</span><span class="o">)</span>
</pre>


<p>Haaa, that's <code>too many exceptions for C++</code>, C++ could not handle more than one exception properly, call terminate directly.
Now go back to position 7, it creates 4 instance of <code>Exception</code> and store it in <code>vector</code>, from my understanding, <code>vector</code> just destroy the objects inside it, call destructor of each object.
Here C++ compiler don't interupt the program met the first throw, continue call the destructor of the second object.</p>
<p>It's really bad idea to throw exception from destructor incase C++ need to safely release the temporary object and don't support multiple exceptions could be thrown in one try catch block.
That's why noexcept is the default added in C++11. You'll see warnings like:</p>
<pre class="code literal-block"><span></span><span class="n">test</span><span class="p">.</span><span class="n">cc</span><span class="p">:</span> <span class="k">In</span> <span class="k">destructor</span> <span class="err">‘</span><span class="k">Exception</span><span class="p">::</span><span class="o">~</span><span class="k">Exception</span><span class="p">()</span><span class="err">’</span><span class="p">:</span>
<span class="n">test</span><span class="p">.</span><span class="n">cc</span><span class="p">:</span><span class="mi">12</span><span class="p">:</span><span class="mi">9</span><span class="p">:</span> <span class="n">warning</span><span class="p">:</span> <span class="n">throw</span> <span class="n">will</span> <span class="n">always</span> <span class="k">call</span> <span class="k">terminate</span><span class="p">()</span> <span class="p">[</span><span class="o">-</span><span class="n">Wterminate</span><span class="p">]</span>
   <span class="n">throw</span> <span class="n">_i</span><span class="p">;</span>
         <span class="o">^~</span>
<span class="n">test</span><span class="p">.</span><span class="n">cc</span><span class="p">:</span><span class="mi">12</span><span class="p">:</span><span class="mi">9</span><span class="p">:</span> <span class="n">note</span><span class="p">:</span> <span class="k">in</span> <span class="k">C</span><span class="o">++</span><span class="mi">11</span> <span class="n">destructors</span> <span class="k">default</span> <span class="k">to</span> <span class="n">noexcept</span>
</pre>
</div>
    </div>
    <aside class="postpromonav"><nav><ul class="pager hidden-print">
<li class="next">
                <a href="../../../../2017/3/2/restore-work-space/" rel="next" title="Restore workspace">Next post</a>
            </li>
        </ul></nav></aside><section class="comments hidden-print"><h2>Comments</h2>
        
        
        <div id="disqus_thread"></div>
        <script>
        var disqus_shortname ="baolonglin",
            disqus_url="https://baolonglin.github.io/posts/2016/12/7/throw-exception-in-destructor/",
        disqus_title="Throw exception in C++ destructor",
        disqus_identifier="cache/posts/2016/12/7/throw-exception-in-destructor.html",
        disqus_config = function () {
            this.language = "en";
        };
        (function() {
            var dsq = document.createElement('script'); dsq.async = true;
            dsq.src = 'https://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script><noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>
</noscript>
    <a href="https://disqus.com" class="dsq-brlink" rel="nofollow">Comments powered by <span class="logo-disqus">Disqus</span></a>


        </section></article><script>var disqus_shortname="baolonglin";(function(){var a=document.createElement("script");a.async=true;a.src="https://"+disqus_shortname+".disqus.com/count.js";(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(a)}());</script><!--End of body content--><footer id="footer">
            Contents © 2020         <a href="mailto:lbl52001@gmail.com">Baolong Lin</a> - Powered by         <a href="https://getnikola.com" rel="nofollow">Nikola</a>         
            
        </footer>
</div>
</div>


        <script src="../../../../../assets/js/all-nocdn.js"></script><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script>
</body>
</html>
